const resp = {
  success: true,
  data: {
    id: 6,
    identityId: null,
    prefix: 'BN',
    firstName: 'Liam',
    lastName: 'Leung',
    email: 'liam@binery.co',
    jobRole: null,
    countryCode: '852',
    phoneNo: '12345678',
    registrationDate: '2022-08-16T04:41:46.786Z',
    oAuthPlatform: null,
    platformId: null,
    emailVerified: true,
    emailVerifiedDate: '2022-08-16T05:50:49.674Z',
    profileCompleted: true,
    profileCompletionDate: '2022-08-16T05:49:36.588Z',
    hubSpotVid: 27951,
    last2FADate: '2022-08-16T05:50:49.674Z',
    bineryLiteUserId: 205,
    bineryLiteToken:
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxpYW1AYmluZXJ5LmNvIiwidXNlcklkIjoyMDUsInVzZXJOYW1lIjoibGlhbUBiaW5lcnkuY28iLCJjb21wYW55SWQiOjAsImlhdCI6MTY2MDYyODk1OSwiaXNzIjoiQmluZXJ5In0.cjaPoBMS2l0FlBNEBHsoXAMEqRm9ICuaQslxxwWJzsg',
    createdAt: '2022-08-16T05:49:12.027Z',
    updatedAt: '2022-08-16T14:09:26.739Z',
    companies: [
      {
        id: 5,
        companyName: 'Binery Limited',
      },
    ],
    company: {
      id: 5,
      prefix: 'CI',
      companyName: 'Binery Limited',
      companyLogo: null,
      brNo: null,
      brProof: null,
      brVerified: false,
      brVerificationCompleteDate: null,
      employeeSize: null,
      revenueClass: null,
      revenueSource: null,
      defaultCurrencyId: 16,
      accountingSwStatus: null,
      accountingSwType: null,
      address: {
        incorporatedCountry: 'Australia',
      },
      billingAddress: null,
      lastBillingDate: null,
      nextBillingDate: null,
      paymentType: null,
      paymentFreq: null,
      paymentStartDate: null,
      lastPaymentDate: null,
      nextPaymentDate: null,
      freeTrial: 'yes',
      freeTrialEndDate: null,
      paymentGatewayId: 'cus_1z0pp10hmgws5a0jtF62fb2ffa1',
      isSignUpFinished: false,
      profileCompleted: true,
      profileCompletionDate: null,
      accountingSwConnected: false,
      accountingSwConnectedDate: null,
      onboardingCallCompleted: false,
      onboardingCallCompletedDate: null,
      previousBooksUploaded: false,
      previousBooksUploadDate: null,
      booksReviewed: false,
      booksReviewedDate: null,
      emailDomain: 'binery.co',
      paymentGateway: 'binery',
      businessDocumentUploaded: false,
      organizationId: 1,
      billingType: 'self-managed',
      createdAt: '2022-08-16T05:49:46.131Z',
      updatedAt: '2022-08-16T05:49:46.131Z',
      industryId: 19,
      organization: {
        id: 1,
        name: 'Binery',
        calendlyLink:
          'https://calendly.com/kenny-binery/45-minute-onboarding-call-with-kenny',
        logo: null,
        createdAt: '2022-08-16T03:24:34.900Z',
        updatedAt: '2022-08-16T03:24:34.900Z',
        deletedAt: null,
      },
      userCompanies: {
        id: 9,
        userId: 6,
        identityId: 13,
        companyId: 5,
        createdAt: '2022-08-16T05:49:12.033Z',
        updatedAt: '2022-08-16T05:49:46.146Z',
      },
    },
    subscription: {
      status: 'unpaid',
      startedAt: '',
      endedAt: '',
    },
    role: 'owner',
  },
  message: 'reAuth',
};
